### ISSUE TITLE
Mock Up

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#10]
Mock Ups, passend zu unseren [Anforderungen](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Funktionale-Anforderungen) designen. 
Der Fokus soll auf den Seiten für die Schüler sitzen.

**Comment by laralngn** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 1 Personenstunden |
| Tatsächlicher Aufwand | 4.5 Personenstunden |

**Comment by Schmarvinius** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 3 Personenstunden |
| Tatsächlicher Aufwand | 8 Personenstunden |
