### ISSUE TITLE
Termin Erstellung (Backend)

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#100]
### Beschreibung
Der Lehrer soll für jeden Kurs, den er unterrichtet, die Möglichkeit haben Termine für Klausuren in den Kalender eintragen zu können. Diese sollen dann in dem Kalender des Lehrers, aber auch der Schüler angezeigt werden. Möglich wäre hier auch noch eine Notification den Schülern zu senden, wenn eine neue Klausur eingetragen wird.

### Task
- [ ] POST Request - zum hinzufügen der Termine in die Datenbank
- [ ] GET Request - erhalten der Termin Daten

### Architektur 
https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Component-Diagramm

### User Story
- #29

**Comment by CodeRider101** [comment]
Dopplung? #237 @Schmarvinius @Kronprinz03 ?
