### ISSUE TITLE
[Informationssystem] News-Eintragung (Frontend)

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#101]
### Feature-Anfrage
Auf der News Seite sollen Admins einen Button haben, um in den Editor Modus zu kommen. Über diesen sollen sie einen Text und ggf. ein Bild hinzufügen können, welche als neuer Post gespeichert werden kann. Dieser Post soll dann für alle auf der News Seite sichtbar sein.

### Eigenschaften
- [ ] Button für Editor Modus
- [ ] Admins sollen im Editor Modus ein Eingabefeld und Bild-Upload haben
- [ ] POST-Request an Backend

### Anwendungsszenarien
Der Admin soll die Möglichkeit haben Informationen auf der Newsseite hinzuzufügen 

### Zusätzliche Informationen

- [Component Diagramm](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Component-Diagramm)
- #38

**Comment by laralngn** [comment]
Issue muss an überarbeitete User Story angepasst werden
