### ISSUE TITLE
[Stundenplan] Stundenplan anzeigen 

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#114]
## Beschreibung
Es soll eine Seite geben, welches den Stundenplan anzeigt. Dabei soll nur der persönliche Stundenplan des jeweiligen Schülers oder Lehrers sichtbar sein. 
Die Stunden sollen in einer Tabellen Ansicht angezeigt werden. 
Dabei sollen die Zeilen beschriftet werden mit den Stundennummern 1-10.
Die Spalten sollen beschriftet werden mit den Tagesnamen plus Datum.
Ein Tabelleneintrag stellt eine Schulstunde dar. 
Die Schulstunde wird durch die Stunden Komponente implementiert, diese nimmt das Fach, den Lehrer und den Raum als Parameter entgegen. 

Durch einen Backend Request werden alle Stunden einer Woche für die Klasse des entsprechenden Schülers  oder für den entsprechenden Lehrer abgerufen. 
Falls ein Zeitslot nicht einer Schulstunde zugeordnet ist, soll der Bereich leer bleiben. 
abruft. 
## Aufgaben
- [x] Tabelle (_NextUI_) implementieren mit richtiger Anzahl und Beschriftung von Zeilen und Spalten
- [x] Tage sind richtig beschriftet mit Datum, und Wochentag
- [x] Stunden Komponente Nutzen, um einen Tabelleneintrag zu füllen
- [x] Stunden an richtiger Stelle in Tabelle einordnen (richtiger Tag, richtiger Stundenslot)
- [x] Daten aus Backend abrufen und anzeigen

## Sonstige Informationen 
- <details>
    <summary>Mockup</summary>
    <IMG src="https://github.com/SE-TINF22B2/G2-Schoolify/assets/115155185/12cfcab3-4ecf-4f25-b435-a6ecba176f96"  alt="image.png"/>
</details>

### User Story
- #14

**Comment by Schmarvinius** [comment]
Phase 0 bzw 1, da die Seite erstellt werden kann aber die richtigen Daten ja aus dem backend gezogen werden müssen

**Comment by CodeRider101** [comment]
Bisher 5 Stunden daran gearbeitet.

**Comment by two-Gee** [comment]
Bisher gearbeitet: 222 Min
