### ISSUE TITLE
[Stundenplan] Stunden für eine Woche 

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#115]
## Beschreibung
Im Backend sollen die Stunden für eine Woche abrufbar sein, um diese im Frontend anzeigen lassen zu können. 
Dafür soll Folgender Web API Endpunkt erstellt werden: 
- GET-Request - /getLessonsForWeek Alle Stunden einer Woche => Parameter: weekStart, courseID (erster Tag der Woche)

Um das zu erreichen soll zuerst eine Methode als Nest.js Service erstellt werden. Die Funktion nimmt den weekStart und die courseID als Parameter entgegen und ruft aus der Datenbank die entsprechenden Stunden ab und speichert diese in einer geeigneten Datenstruktur. Die Funktion soll diese Stunden returnen. 
Anschließend soll ein Controller implementiert werden, der diese Funktion als Service aufruft.
Der Controller empfängt als Request Parameter weekStart und courseID.
Das Ergebnis der Funktion soll nun vom Controller als WEB API bereitgestellt werden.

## Aufgaben

- [x] Service Methode implementieren mit Parametern weekStart und courseID
- [x] Logik implementieren die Stunden von DB abruft und diese zurückgeben
- [x] Controller Methode implementieren 
- [x] Service Methode aufrufen und Ergebnis über WebAPI zur Verfügung stellen
- [x] Tests schreiben

### Architektur
- [Component Diagramm](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Component-Diagramm)
### Abhängigkeiten 
- keine

### User Story
- #14

**Comment by CodeRider101** [comment]
Bisher 0.5 Stunden daran gearbeitet.

**Comment by tilwbr** [comment]
10 minuten für pr review und approval :)

**Comment by two-Gee** [comment]
Also die Subject ID bringt mir ziemlich wenig haha, 
ich brauche den Subject Namen und den Timeslot.
