### ISSUE TITLE
[Informationssystem] Klassenbuch (Backend)

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#120]
### Feature-Anfrage
Es sollten alle Informationen die wichtig für eine Klasse sind dargestellt werden. #26 #27

### Eigenschaften
- [ ] Es sollten neue Einträge erstellt werden könne
- [ ] Bestehende Einträge sollten eingesehen werden können

### Anwendungsszenarien
Es sollte eine eigene Seite geben für "digitale Klassenbücher", wo Lehrer zwischen den Klassen auswählen können, um dann für die jeweilige Klasse einen Klassenbucheintrag für einen bestimmten Tag zu erstellen. Zudem soll einen alter Tag ausgewählt werden können, um alte Einträge anzeigen zu lassen.
Der Lehrer soll für jeden seiner Termine (Stunden) auf eine Übersichtsseite kommen können, in der aufgelistet ist, welche Schüler alle entschuldigt sind und welche anwesend sein sollen. Dadurch kann die Anwesenheit aller Schüler korrekt kontrolliert werden und unentschuldigtes Fehlen fällt schnell auf.

### Beispiele
/

### Mögliche Implementierungen
- [ ] GET-Request - Abmeldungen/Krankmeldungen
- [ ] GET-Request - Hausaufgaben und Notizen
- [ ] POST-Request - Neue Einträge erstellen

### Zusätzliche Informationen
/

**Comment by tilwbr** [comment]
- [ ] create own service, module and controller absence

**Comment by tilwbr** [comment]
- [ ] classbook service, module and controller
