### ISSUE TITLE
[Informationssystem + Mensaplan] Dashboard / Übersichtsseite

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#131]
### Feature-Anfrage
Nach dem Einloggen auf die Seite möchte ich auf eine Startseite gelangen auf der mein heutiger Stundenplan und Mensa Plan steht, dazu sollen News und anstehende Termine angezeigt werden. #122

### Eigenschaften
- [ ] Anzeigen des Stundenplan für heute
- [ ] Anzeigen des Mensaplan für heute
- [ ] Anzeigen aktueller News
- [ ] Anzeigen eines Kalenders
- [ ] Anzeigen anstehender Termine
- [ ] Einzelne Requests im Backend für das anzeigen o.g. Komponenten (da diese nur einzelne Tage anzeigen und nicht alle)
- [ ] Requests aus dem Frontend ans Backend

### Anwendungsszenarien
Schüler und Lehrer sollen eine Seite haben auf der sie gebündelt die wichtigsten Informationen finden.

### Beispiele
[Dashboard](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Funktionale-Anforderungen#informationssystem)

### Mögliche Implementierungen
/

### Zusätzliche Informationen
/

**Comment by Kronprinz03** [comment]
Keine User Story verlinkt
