### ISSUE TITLE
[Mensaplan] Speise Erstellung Admin (Frontend)

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#134]
## Beschreibung 
Auf der Mensaplan Seite sollen Admins ein Eingabeformular für das Hinzufügen von Gerichten haben.
In dem Eingabeformular soll es mehrere Eingabefelder mit zugehörigen Labels und optional Placeholdern geben. Es soll je ein Eingabefelder für:
- Titel des Gerichts
- Kurzversion des Titles
- Allergene
- Preis
- Beschreibung
- Url für ein Bild
Das Feld für die Kurzversion des Titels und für die Allergene sollen als optional gekennzeichnet sein.
Zusätzlich soll es ein Auswahlfeld geben, um ein oder mehrere Tag auszuwählen, für die das Gericht eingetragen werden soll. Weiter soll es eine Radio Button Gruppe geben, um die Ernährungskategorie auszuwählen. Zuletzt soll es einen Button geben, um ein Bild auszuwählen und hochzuladen.

Unter den Eingaben sol es abschließend noch einen Button geben, um das Gericht zu speichern und an das Backend zu senden.

## Aufgaben 
- [x] Eingabeformular als Card _(NextUI)_ mit Titel implementieren
- [x] Eingabefelder _(NextUI)_ mit Label implementieren und ggf. als optional kennzeichnen
- [x] Select _(NextUI)_ für Tage implementieren (mind. für 2 Wochen)
- [x] Radio Buttons _(NextUI)_ für Kategorie implementieren
- [x] Input _(NextUI)_ für Link einen Bildes implementieren
- [x] Button _(NextUI)_ zum Speichern implementieren
- [x] Bei Klick auf den Button Daten ans Backend senden
- [x] Bestätigungstoast bei erfolgreichem Hinzufügen

### Abhängigkeiten
- #135

### Mockup
<img width="820" alt="image" src="https://github.com/SE-TINF22B2/G2-Schoolify/assets/115155205/d2aa4347-19f7-4ccf-9822-9ed638adbbe2">

## User Story
- #124

**Comment by Kronprinz03** [comment]
Keine User Story

**Comment by laralngn** [comment]
11:57 - 13:10 Uhr (Kimai geht nicht)
