### ISSUE TITLE
[Mensaplan] Speisen Erstellung (überarbeiten)

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#135]
## Beschreibung
Wenn ein Admin ein Gericht dem Mensaplan über ein Eingabeformular hinzufügt, soll es in der Datenbank gespeichert werden. Dafür soll es einen Endpunkt geben, welcher ein Objekt mit den Daten des Gerichts entgegennimmt und diese in der Datenbank speichert.
Jedes Gericht soll einen Titel, einen Preis, ein Bild, eine Kategorie (vegan, vegetarisch, Rindfleisch, Schweinefleisch oder Fisch), sowie Allergene haben. Optional soll es bei langen Namen noch eine Kurzversion des Titels geben. Auch optional ist noch eine Beschreibung des Gerichts (z.B. welche Beilagen es gibt).

## Aufgaben
- [x] Controller implementieren: POST /canteenplan/addMeal
- [x] Service Methode implementieren mit entsprechenden Parametern
- [x] Logik implementieren, die Gericht in Datenbank abspeichert
- [x] Controller Methode implementieren 
- [x] Service Methode aufrufen und Ergebnis über WebAPI zur Verfügung stellen
- [x] Tests schreiben

### Abhängigkeiten
- Keine

### Architektur 
<img width="1320" alt="image" src="https://github.com/SE-TINF22B2/G2-Schoolify/assets/115155205/03648adf-4f2f-4732-b8e4-34ce98aecb28">

### User Story
- #124

**Comment by tilwbr** [comment]
nochmal 51 Minuten

**Comment by tilwbr** [comment]
sobald db angepasst wurde, kann auch die POST request angepasst werden

**Comment by tilwbr** [comment]
auch hier dank model anpassung gefixed
