### ISSUE TITLE
Responsive Design for mobile

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#149]
### Beschreibung

Es sollten die vorhanden Views aus den Mock Ups auch auf kleineren Geräten aufgerufen werden können.
Zur Ermöglichung sollen weiter Figma Views erstellt werden, die auf kleine Geräte angepasst sind um am Ende als Vorbild für unsere Webseite bei der Implementierung von Responsive Designs zu dienen.

### Task
- [x] Erstellung der Responsive Views

**Comment by tilwbr** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 1 Personenstunden |
| Tatsächlicher Aufwand | 4 Personenstunden |
