### ISSUE TITLE
Ordnernstruktur anlegen Frontend

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#155]
Ordnerstruktur im Wiki angeben. 
Durch die Struktur soll ersichtlich werden in welchen Ordner welche Implementierung erfolgen soll. 
Dadurch soll erreicht werden, dass nicht jeder der an einer Implementierung arbeitet es woanders speichert. 

Die Struktur soll im Projekthandbuch im Wiki dokumentiert werden

**Comment by tilwbr** [comment]
Habe die Ordnerstruktur in das Projekthandbuch übertragen :)

**Comment by tilwbr** [comment]
Ich übersetz das alles nur mal ins englische auch
