### ISSUE TITLE
Umfrage erstellen

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#162]
# Task

- [x] Es soll die Möglichkeit geben allgemein Feedback zu geben was machen wir gut was sollten wir verbessern
- [x] Es sollen allgemeine Fragen vorhanden sein am besten noch etwas bei dem wir Statistiken nachher zeigen können 

-> Feedback kannst du an @Kronprinz03 weiter geben oder selbst ein Mural erstellen

**Comment by CodeRider101** [comment]
user | estimated effort | actual effort
-- | --| --
@CodeRider101  |0.5h | 0.5h
