### ISSUE TITLE
[Kontoverwaltung] Lehrer Löschen und Update

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#183]
### Feature-Anfrage

Lehrer Löschen und Updaten <User-Story>

### Eigenschaften
- [ ] update
- [ ] löschen

### Anwendungsszenarien

Damit können Admins Lehrer die die Schule verlassen haben aus ihrer Datenbank löschen falls es nötig ist, wenn sich die Daten eines Lehrers geändert haben, kann der Admin die Daten einfach abändern.

### Beispiele
/

### Mögliche Implementierungen

- DELETE Request
- Update Request

**Comment by Kronprinz03** [comment]
Keine User Story verlinkt
