### ISSUE TITLE
[SE] User Story Funktionen erweitern 

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#241]
### Erklärung: 
Momentan sind in den User Story bestimmte Funktionen noch nicht ausreichend definiert. Für die fehlenden Feature sollen neue User-Stories erstellt oder existierende User-Stories erweitert werden. Für die neuen Funktionen sollen dann auch direkt die Issues erstellt werden.

### Eigenschaften

- [x]  Fehlende Funktionen hinzufügen / erstellen 

### Anwendungsszenarien

Nehmen wir als Beispiel die User Story #44 (Als Lehrer möchte ich die Räume, falls es möglich ist ändern …): Man möchte sicher nicht nur eine Funktion, um Raumzuordnungen zu ändern, sondern auch
- Räume erstmalig zuordnen
- Raumzuordnungen entfernen
- Wo sind diese Anforderungen (bzw. die entsprechenden User Stories)?
 
Um Räume überhaupt zuordnen zu können, müssen sie zunächst irgendwo angelegt werden können. Ggf. mit einer Unterscheidung nach normalen Klassenräumen und Spezialräumen (Musikraum, Sporthalle, Labore für Naturwissenschaften etc.). D.h. man benötigt eine Verwaltung der Raum-Stammdaten. Wo findet man die?
 
Die Räume sind nur ein Teilaspekt eines größeren Themas, nämlich der Stundenplan-Planung. Was hier fehlt, ist eine Zusammenstellung der Anforderungen auf detaillierter Ebene nach solchen Themen wie „Raumverwaltung“, „Stundenplan-Planung“ etc.

 
In einem realen Projekt würde man sich z.B. mit dem Team, welches die Stundenplan-Planung durchführt, zusammensetzen und sämtliche Anforderungen und Funktionalitäten zu diesem Thema entlang der Planungsprozesse erheben. D.h. eine solch isolierte Anforderung wie #44 würden Sie nicht bekommen. Stattdessen bearbeitet man ein Thema gesamtheitlich und bekommt dann eine ganze Liste inhaltlich/fachlich zusammenhängender Anforderungen. Die müsste man dementsprechend in diesem Gesamtzusammenhang dokumentieren, denn
die Anwender müssen einen Überblick über solche Gesamthemen haben, um z.B. erkennen zu können, ob sie sämtliche Funktionalitäten dazu spezifiziert haben oder ob Dinge fehlen oder widersprüchlich sind
die Software-Entwickler werden solche Themen gesammelt umsetzen; es macht wenig Sinn, dass z.B. ein Entwickler die Funktion für „Raumzuordnung ändern“ und ein anderer die Funktion „Raum erstmalig zuordnen“ implementiert

Zum Thema Stundenplan-Planung würden Sie in einem Anforderungs-Workshop mit dem Planungsteam z.B. folgendes erfahren:
Das Planungsteam startet drei Monate vor Beginn eines Schuljahres mit der Planung und erstellt iterativ Planungsvarianten
Für die Planung werden als Basisdaten benötigt
Lehrer
die zeitliche Verfügbarkeit der Lehrer (manche arbeiten z.B. in Teilzeit)
Räume
Fächer (unterteilt nach Klassenstufen, Wahl- und Pflichtfächern etc.)
Klassen (u.a. Parallelklassen)
All diese Basisdaten müssen selbstverständlich auch verwaltet (angelegt, geändert, gelöscht) werden können (dazu gehören User Stories wie #130, #126, #125, #31)
Sobald eine Planungsvariante mit einem gewissen Reifegrad vorliegt, wird sie für das gesamte Lehrerkollegium sichtbar gemacht, so dass von dort Feedback eingesammelt werden kann
Wenn das Feedback eingearbeitet ist, wird die finale Stundenplanversion erstellt und zwei Wochen vor Beginn des Schuljahres den Schülern zur Verfügung gestellt (darüber kommt man zu Aspekten wie #14)
Während des Schuljahres kommt es zu Umplanungen, z.B. wenn Lehrkräfte längerfristig erkranken oder wenn sie die Schule während des Schuljahres verlassen
Nach Ende des Schuljahres verlieren die Schüler den Zugriff auf die Stundenpläne. Das Planungsteam kann alte Planungen jedoch nutzen, um neue Planungen auf Basis von Kopien alter Planungen zu erstellen
Auf dieser Basis würde man sich überlegen, welche Einzelfunktionen dafür notwendig sind, wie das UI dazu aussieht etc.

**Comment by two-Gee** [comment]
User Stories, die noch fehlen: 

- [Informationssystem] Terminkalender Schüler

**Comment by laralngn** [comment]
Wird der Punkt "[Informationssystem] Anzeigen aktueller Nachrichten für Lehrer, Schüler" nicht schon durch die User Story #122 [Stundenplan, Mensaplan, Informationssystem] Übersichtsseite Schüler/Lehrer abgedeckt?

**Comment by laralngn** [comment]
User Story #28 (Noteneinsicht Klassenlehrer) fehlt in den funktionalen Anforderungen

**Comment by two-Gee** [comment]
> Wird der Punkt "[Informationssystem] Anzeigen aktueller Nachrichten für Lehrer, Schüler" nicht schon durch die User Story #122 abgedeckt?

Ja schon, die User Story ist aber auf sehr viel bezogen und deshalb kein 'eigener' Funktionsbaustein. Wir können die User Story drin lassen um das Anzeige der ganzen Informationen auf einen Blick zu verdeutlichen, aber dann sollten wir die einzelnen Aspekte schon noch als eigene User Story abbilden.

**Comment by CodeRider101** [comment]
@laralngn @two-Gee könnt ihr bitte noch eure Zeiten eintragen und die fehlenden Informationen bei den Projects nachtragen <3

**Comment by two-Gee** [comment]
gebrauchte Zeit : 53 min

**Comment by laralngn** [comment]
Gebrauchte Zeit: 1h 54min
