### ISSUE TITLE
[Mensaplan] Anfragen für Mensaplan 

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#245]
## Beschreibung
Das Backend des Mensaplans ist für die Verwaltung und Übermittlung der Mensaplan Daten an das Frontend zuständig.

Beim Öffnen der Mensaplan Seite sollen direkt die Informationen über die Gerichte dieser Woche vom Backend geholt werden. Dafür soll es einen Endpunkt geben, welcher ein Objekt mit den Daten des Wochenplans für die aktuelle Woche übergibt. Jeder Wochentag soll Unterobjekte mit den verschiedenen Gerichten haben. Jedes Gericht soll einen Titel, einen Preis, ein Bild, eine Kategorie (vegan, vegetarisch, Rindfleisch, Schweinefleisch oder Fisch), sowie Allergene haben. Optional soll es bei langen Namen noch eine Kurzversion des Titels geben. Auch optional ist noch eine Beschreibung des Gerichts (z.B. welche Beilagen es gibt).
Es soll außerdem einen Endpunkt geben, um die Daten für die nächste Woche zu holen. 

## Aufgaben
- [x] Methode zum Formatieren der Daten als Service implementieren mit Parameter Woche
- [x] Controller implementieren: GET /canteenplan/thisweek
- [x] Controller implementieren: GET /canteenplan/nextweek
- [x] Controller ruft Service auf

### Abhängigkeiten
- Keine

### Architektur
<img width="1320" alt="image" src="https://github.com/SE-TINF22B2/G2-Schoolify/assets/115155205/df37917e-2573-46c1-b815-99cbc7871527">

## User Story
- #37

**Comment by tilwbr** [comment]
62 Minuten

**Comment by CodeRider101** [comment]
10 min für PR approven

**Comment by laralngn** [comment]
Die Endpunkte liefern nicht die richtigen Daten. 
Wie im Issue beschrieben, werden folgende Daten gebraucht:
- Titel 
- Preis 
- Bild
- Kategorie (vegan, vegetarisch, Rindfleisch, Schweinefleisch oder Fisch)
- Allergene
- Optional bei langen Namen noch eine Kurzversion des Titels 
- Optional noch eine Beschreibung des Gerichts (z.B. welche Beilagen es gibt)

Muss vermutlich auch in #135 angepasst werden.

**Comment by tilwbr** [comment]
du bekommst ein array, in dem für jeden tag ein array mit food ist, dort sind alle benötigten informationen drin

**Comment by laralngn** [comment]
Das sind falsche Informationen. Kann sein, dass die Datenbank auch dementsprechend angepasst werden muss.

**Comment by tilwbr** [comment]
[
	[
		{
			"foodID": 2,
			"name": "Pizza",
			"description": "Cheesy pizza.",
			"ingredients": "Check the meal description",
			"calories": "500",
			"day": "2024-06-10T17:46:27.000Z",
			"allergies": "None",
			"extra": "Extra Cheese",
			"foodWeekFoodWeekID": 2
		}
	],
	[
		{
			"foodID": 4,
			"name": "Salad",
			"description": "Healthy salad.",
			"ingredients": "Check the meal description",
			"calories": "500",
			"day": "2024-06-11T17:46:27.000Z",
			"allergies": "None",
			"extra": "Extra Cheese",
			"foodWeekFoodWeekID": 2
		}
	],
	[],
	[],
	[]
]

hier ist drin:
- [x] titel
- [ ] preis -> sobald es in der db steht kriegst du das dort auch zurück
- [ ] bild -> nicht enthalten in db, kriegst du aber auch sobald es dort drin ist
- [ ] kategorie -> nicht enthalten, kriegst du aber auch sobald es in db ist
- [x] allergene
- [x] optional = extra

**Comment by tilwbr** [comment]
liegt also nur am model in der db, sobald das aber geupdated ist, kriegst du hier also auch alles

**Comment by tilwbr** [comment]
durch model anpassung gefixed
