### ISSUE TITLE
[SE] Planung des restlichen Projektes

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#251]
### Beschreibung

Es soll ein Ablaufplan erstellt werden wann wir mit unserem Projekt fertig werden

**Comment by CodeRider101** [comment]
- [Roadmap](https://github.com/orgs/SE-TINF22B2/projects/22/views/1)
  - [Wiki-Eintrag](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Projektplanung-bis-Abgabe)
  - Eingeschränkt auf Login, Stundenplan und Mensaplan
