### ISSUE TITLE
[SE] User Stories überarbeiten 

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#253]
### Task 
- [x] User Stories auf Vollständigkeit und Inkonsistenzen prüfen

**Comment by two-Gee** [comment]
Benachrichtigungen zu Informationssystem in funktionalen Anforderungen hinzugefügt

**Comment by two-Gee** [comment]
gebrauchte Zeit bisher: 2:42 stunden

**Comment by laralngn** [comment]
Gebrauchte Zeit: 1h 9min

**Comment by laralngn** [comment]
Issue #92 und Issue #94 sind sich sehr ähnlich. Beide bei #31 verlinkt. 
Sollte eins entfernt werden bzw. die Issues zu einem gemerged werden?

**Comment by laralngn** [comment]
Issue #182 closen?

**Comment by laralngn** [comment]
Issues müssen noch erstellt werden für:
- [ ] #263

**Comment by laralngn** [comment]
Issue #141, #140, #207 brauchen ein Oberissue
