### ISSUE TITLE
[SE] Projekthandbuch erweitern 

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#254]
### Task

- [x] Prozesse beschreiben Big Picture -> F.A -> U.S -> Issues
     https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Projekthandbuch#prozesse
- [x] Labels erklären 
    https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Projekthandbuch#labels
- [x] Scope
    https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Projekthandbuch#projektscope

**Comment by CodeRider101** [comment]
Zeitaufwand:
Name | Zeit
-- | --
@tilwbr | 
@CodeRider101 | 33min

**Comment by laralngn** [comment]
Die Prozessbeschreibung stimmt nicht ganz, denn das **Big Picture als oberste Stufe fehlt**. 
Außerdem sollte die Beschreibung nicht unbedingt im Big Picture selbst stehen.

**Comment by laralngn** [comment]
Die Verknüpfungen der einzelnen Bereiche, welche die Use-Cases letztendlich darstellen soll, fehlt.

**Comment by CodeRider101** [comment]
@laralngn  schau nochmal nach. Wir hatten das geändert. Wenn immernoch was fehlt schreib einf ausführlich was fehlt

**Comment by laralngn** [comment]
Mit der Beschreibung der Prozesse war konkret gemeint, dass der Prozess, wie sich die einzelnen Komponenten (Big Picture, Anforderungen etc.) aufeinander beziehen und wie diese die Themen immer weiter aufgliedern. Es war nicht gemeint, die einzelnen Komponenten an sich zu beschreiben, sondern die Zusammenhänge und wie diese Komponenten zusammen unsere Use Cases darstellen.

**Comment by laralngn** [comment]
Estimated und actual Effort fehlen im Projekt
