### ISSUE TITLE
[SE] Problem Externer Anbieter für Informationen

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#285]
# Beschreibung 
Unser Projekt soll jetzt im Backend einen externen Anbieter nutzten zur Erhaltung der Daten. Es soll nun ermittelt werden welche Probleme bei dieser Änderung aufkommen und welchen Umfang die Anpassung an dem Programm hätten

**Comment by tilwbr** [comment]
@Kronprinz03 sind mehr Informationen über die genaue Anforderungen bekannt?

**Comment by tilwbr** [comment]
|Person | Zeit | 
|-------| ---- | 
|@tilwbr|28min|
