### ISSUE TITLE
[SE] Neue Issues erstellen 

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#286]
# Beschreibung 
Wir haben die letzten Wochen viele Verbesserungen und Anpassungen an unseren FA und User Stories jetzt sollen Issues neu erstellt werden, nach dem Muster unten. 

## Idee
 User Stories als "Oberissues" nehmen, um Dopplungen zu vermeiden
Anstatt nur ein Frontend und ein Backend Issue pro User Story zu machen, direkt detaillierte Issues erstellen und diese den User Stories zuordnen. 

### Zuordnung in User Stories: 
Frontend:
- Issue 1
- Issue 2

Backend: 
- Issue 1 
- Issue 2

### Beschreibung 
Genaue Beschreibung um was es geht und was in dem Issue umgesetzt werden soll. 
-> Möglichst implementierungsnah / technisch, **Dopplungen mit User Story vermeiden!**
### Aufgaben 
Beschreibung der Aufgaben als Task Liste, dabei genau auf Implementierungschritte eingehen
### Zusätzliche Informationen 
- Ggf. Abhängigkeiten zu anderen Issues verlinken 
- Bei Frontend: entsprechendes Figma Mockup einfügen
- Bei Backend: entsprechende Architektur einfügen
### User Story
Zugehörige User Story verlinken

**Comment by Kronprinz03** [comment]
|Person | Zeit |
|-------| ---- |
|@Kronprinz |  33min |

**Comment by two-Gee** [comment]
Issues erstellen: 
|Issue|Verantworlich|
|--|---|
|#274|@Schmarvinius|
|#273|@tilwbr|
