### ISSUE TITLE
[Kontoverwaltung] Login Seite

### ISSUE THREAD

**Issue by laralngn** [SE-TINF22B2/G2-Schoolify#290]
## Beschreibung 
Auf einer eigenen Login Seite soll es eine Willkommensnachricht und eine Login Card mit entsprechender Eingabemaske geben. 
Die Card soll zwei Eingabefelder haben, eins für die E-Mail und eins für das zugehörige Passwort. Über den Eingabefeldern soll ein auffordernder Hinweis zur Anmeldung stehen z.B. "Melde dich mit deiner E-Mail und deinem Passwort an.". Unter den Eingabefeldern soll ein Button zur Anmeldung sein. 
Beim Klicken des Anmeldebuttons sollen die Eingaben ans Backend gesendet werden, um den Nutzer zu authentifizieren. Bei korrekter Eingabe soll der Nutzer zur persönlichen Startseite geleitet werden. Bei falschen Eingaben soll eine Fehlermeldung bei den Eingabefeldern angezeigt werden.

## Aufgaben 
- [ ] Login Seite mit Willkommensnachricht implementieren
- [ ] Login Card mit Hinweis implementieren
- [ ] E-Mail Eingabefeld implementieren
- [ ] Passwort Eingabefeld implementieren
- [ ] Anmelde Button implementieren
- [ ] Bei Klick auf den Button die Eingaben ans Backend senden
- [ ] Fehlermeldungen bei ungültigen Eingaben anzeigen
- [ ] Weiterleitung an die Startseite bei korrekter Eingabe

### Abhängigkeiten
- #291

### Mockup
<img width="937" alt="image" src="https://github.com/SE-TINF22B2/G2-Schoolify/assets/115155205/88438cc1-eeba-4d4e-b1da-ade505f1d2c3">

## User Story
- #23

**Comment by two-Gee** [comment]
bisher daran gearbeitet: 76 + 111 + 57 =  244 min
