### ISSUE TITLE
Datenmodell anpassen

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#323]
Das Datenmodell in Supabase müssen die Tabellen Meal und Lesson noch angepasst werden:

Bei Lesson:
- startTime zu day ändern (nur Datum keine Uhrzeit)
- duration entfernen 

- timeslot hinzufügen (integer von 1 bis 10)

Bei Meal:
- Ingredients entfernen 
- Calories entfernen 
- Extra entfernen

- Preis hinzufügen
- Kategorie (vegan, vegetarisch, Rindfleisch, Schweinefleisch oder Fisch) hinzufügen
- Optional bei langen Namen noch eine Kurzversion des Titels

**Comment by CodeRider101** [comment]
@tilwbr @CodeRider101  pr review jeweils 5min
