### ISSUE TITLE
[MockData] Erstellen und anpassen von Mockdaten

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#327]
### Beschreibung
Manche durch die Änderungen im Projekt haben sich auch die models auf der Datenbank geändert und deswegen müssen nun auch die Mockdaten nachverbessert und neu erstellt werden  

### Task
- [ ] Food für 2 Wochen je mind. 1 Essen pro Tag
- [ ] Studenplan je 6 Studen pro Tag für 2 Wochen

**Comment by tilwbr** [comment]
- wichtig bei dem jeweiligen FoodWeek Objekt: Zeitverschiebung beim erstellen beachten, dass die Uhrzeit auf 0 Uhr vom Montag gestellt ist :)
