### ISSUE TITLE
Technolgien beschreiben

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#35]

**Comment by CodeRider101** [comment]
Geschätzter Aufwand: 0.5h
-> Hat mich 15 min gekostet (0.25h)

**Comment by Schmarvinius** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 0.5 Personenstunden |
| Tatsächlicher Aufwand | 0.5 Personenstunden |

**Comment by Kronprinz03** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 1 Personenstunden |
| Tatsächlicher Aufwand | 1 Personenstunden |

**Comment by tilwbr** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 0.5 Personenstunden
Tatsächlicher Aufwand | 0.5 Personenstunden

**Comment by two-Gee** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 0.5 Personenstunden
Tatsächlicher Aufwand | 1 Personenstunden
