### ISSUE TITLE
Abnahmekriterien formulieren

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#36]
Abnahmekriterien zu den vorhanden Anforderungen

**Comment by laralngn** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 1 Personenstunden |
| Tatsächlicher Aufwand | 0.5 Personenstunden |

**Comment by two-Gee** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 0.5 Personenstunden |
| Tatsächlicher Aufwand | 0.5 Personenstunden |

**Comment by tilwbr** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 1 Personenstunden
Tatsächlicher Aufwand | 0.5 Personenstunden

**Comment by CodeRider101** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 1 Personenstunden
Tatsächlicher Aufwand | 0.5 Personenstunden

**Comment by Kronprinz03** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 0.5 Personenstunden |
| Tatsächlicher Aufwand | 0.5 Personenstunden |
