### ISSUE TITLE
[SE] Architektur dokumentieren

### ISSUE THREAD

**Issue by laralngn** [SE-TINF22B2/G2-Schoolify#40]
- [x] Komponentendiagramme für logische Sicht 
- [ ] Punktuelle Dokumentation besonderer Aspekte der untersten Ebene der logischen Sicht
- [x] 1 Deploymentdiagramm für Verteilungssicht
- [ ] evtl. Sequenzdiagramme oder Aktivitätendiagramme für besondere Aspekte der Prozesssicht

**Comment by CodeRider101** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 0.5 Personenstunden
Tatsächlicher Aufwand |
