### ISSUE TITLE
Problem zum Big Picture hinzufügen

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#42]
Problem, das wir mit unserem Projekt lösen wollen genauer beschreiben und zum Big Picture hinzufügen

**Comment by laralngn** [comment]
Problem wurde zum Punkt **Übersicht** hinzugefügt

**Comment by laralngn** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 0.5 Personenstunden |
| Tatsächlicher Aufwand | 0.5 Personenstunden |
