### ISSUE TITLE
User Stories überarbeiten

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#62]
Task:
Jeder soll die bis jetzt erzeugten User-Stories sich einmal anschauen Feedback geben und eventuelle Meinungsverschiedenheiten oder Fehler in die Kommentare schreiben, damit sie für das nächste Meeting besprochen werden können.

**Comment by laralngn** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 0.5 Personenstunden |
| Tatsächlicher Aufwand | 2.5 Personenstunden |

**Comment by two-Gee** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 1 Personenstunden
Tatsächlicher Aufwand | 0.5 Personenstunden

**Comment by tilwbr** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 0.5 Personenstunden
Tatsächlicher Aufwand | 0.5 Personenstunden

**Comment by CodeRider101** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 1 Personenstunden
Tatsächlicher Aufwand | 0.5 Personenstunden

**Comment by Kronprinz03** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 1 Personenstunden
Tatsächlicher Aufwand | 1 Personenstunden
