### ISSUE TITLE
Anforderungen aus Anwendersicht formulieren (Wiki)

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#65]
Bisher hatten wir nur User Stories und stichpunktartig Features festgelegt. 
Dies sollte ergänzt werden um genau definierte Anforderungen aus Anwendersicht in natürlicher Sprache und ggf. mit Sprachvorlagen.

**Comment by two-Gee** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 2 Personenstunden
Tatsächlicher Aufwand | 3 Personenstunden

**Comment by laralngn** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 1 Personenstunden |
| Tatsächlicher Aufwand | 2 Personenstunden |
