### ISSUE TITLE
User Stories erstellen

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#7]

**Comment by Kronprinz03** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 5 Personenstunden |
| Tatsächlicher Aufwand | 4 Personenstunden |

**Comment by laralngn** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 0.5 Personenstunden |
| Tatsächlicher Aufwand | 1 Personenstunden |

**Comment by two-Gee** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 0.5 Personenstunden
Tatsächlicher Aufwand | 0.5 Personenstunden

**Comment by tilwbr** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 1 Personenstunden
Tatsächlicher Aufwand | 1 Personenstunden

**Comment by CodeRider101** [comment]
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 0.5 Personenstunden
Tatsächlicher Aufwand | 0.5 Personenstunden

**Comment by Schmarvinius** [comment]
| Aufwand | Zeit |
| Geschätzter Aufwand | 1 Personenstunden |
| Tatsächliche Aufwand | 1 Personenstunden |
