### ISSUE TITLE
Datenbank anbinden

### ISSUE THREAD

**Issue by two-Gee** [SE-TINF22B2/G2-Schoolify#8]
Testen und hinzufügen einer MongoDB Anbindung über Prisma.

Geschätzter Zeitaufwand: 0,5h

**Comment by Kronprinz03** [comment]
| Aufwand | Zeit |
| ----------- | ----------- |
| Geschätzter Aufwand  | 0.5 Personenstunden |
| Tatsächlicher Aufwand | 0.5 Personenstunden |
