### ISSUE TITLE
Issue definieren 

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#93]
### Beschreibung
Es sollen aus den vorhandenen User Stories die passenden Issues erstellt werden

### User Stories für Issues
- [x] #14 
- [x] #15 
- [x] #16 
- [x] #17 
- [x] #18 
- [x] #19 
- [x] #20 
- [x] #22 
- [x] #23 
- [x] #24 
- [x] #26
- [x] #27
- [x] #28 
- [x] #29
- [x] #30 
- [x] #31
- [x] #32 
- [x] #33 
- [x] #34 
- [x] #37 
- [x] #38 
- [x] #43 
- [x] #44 
- [x] #123 
- [x] #124 
- [x] #125 
- [x] #126 
- [x] #127 
- [x] #128 
- [x] #129 
- [x] #130

**Comment by CodeRider101** [comment]
## Personenstunden
Aufwand | Zeit
-- | --
Geschätzter Aufwand | 5h
@Kronprinz03 tatsächlicher Aufwand | 2h
@Schmarvinius  tatsächlicher Aufwand | 2h
@CodeRider101 tatsächlicher Aufwand | 2h
Tatsächlicher Aufwand | 6h
