### ISSUE TITLE
[Informationssystem] Terminkalender

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#95]
### Feature-Anfrage
Der Schüler soll eine Kalender Ansicht haben mit allen wichtigen extra Information z.B. Klausuren.
Dazu soll es eine Liste geben in der alle Klausuren sollen sortiert nach Datum aufgelistet sind. Sie sollen auch die Möglichkeit haben die Aufgaben als Fertig zu markieren.
Der Kalender und die Liste sollen auch über Filter Funktionen verfügen z.B. nach Fach.
### Eigenschaften

- [ ] Kalender zeigt Klausuren an 
- [ ] Liste zeigt allgemeine Events und Klausuren an 
- [ ] Beide könne sortiert werden z.B. nach Datum
- [ ] Filter Möglichkeiten

**Extras**
- [ ] Farbige Markierung von unterschiedlichen Prioritäten und Events 

### Anwendungsszenarien

1. Schüler will seine Arbeiten im Blick behalten und schaut deswegen welche Klausur wann als nächstes ansteht

### Beispiele
[Mockup Informationssystem](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Funktionale-Anforderungen)

### Mögliche Implementierungen

Die Kalender-Funktion könnte durch eine Komponente im Next.js Frontend implementiert werden. Für die Darstellung der Daten kann eine Bibliothek wie FullCalendar verwendet werden.
Die Komponente sollte zwei Ansichten haben: eine Kalenderansicht und eine Aufgabenlistenansicht. Beide Ansichten sollten auf die gleichen Daten zugreifen, diese aber unterschiedlich darstellen: in der Kalenderansicht werden visuell das Datum, die Uhrzeit und der Titel der Termine angezeigt, während die Aufgabenlistenansicht zusätzliche Details wie Beschreibungen und Check-Boxen zum Markieren der erledigten Aufgaben anzeigt.
Die Listenansicht und die Kalenderansicht sollten filter- und sortierbar sein. Dafür könnte man zum Beispiel die React.useState und React.useEffect Hooks in Verbindung mit den JavaScript Array Methoden .filter und .sort verwenden.

### Zusätzliche Informationen
- #22
- #29 
- [Mockup Informationssystem](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Funktionale-Anforderungen)

**Comment by Schmarvinius** [comment]
Frontend I guess?

**Comment by laralngn** [comment]
Beschreibung und Anwendungsszenarien müssen überarbeitet werden.
Aufgaben wurden aus Feature entfernt.
