### ISSUE TITLE
[Mensaplan] Benutzer sollen den Mensaplan einsehen können  

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#98]
### Feature-Anfrage

Integration einer Mensaplan-Komponente in die Schulwebseite, die es Benutzern ermöglicht, den wöchentlichen Speiseplan der Schulcafeteria einzusehen.

### Eigenschaften

- [x]  Implementierung der Mensaplan-Komponente, die den wöchentlichen Plan darstellt.
- [x]  Anzeigen detaillierter Informationen für jeden Tag, einschließlich Name der Speisen, Zutaten, Allergene und Preis.
- [ ]  Implementierung der Funktionen zur Interaktion mit dem Backend, um den wöchentlichen Plan zu erhalten.
- [x]  Hinzufügen von Funktionen und Bedienelementen, um zwischen den Tagen zu wechseln.

### Anwendungsszenarien
- Ein Nutzer möchte den Mensaplan für die nächste Woche sehen und fordert eine Anzeige an.
- Ein Administrator muss Änderungen an der Speisekarte für den kommenden Tag vornehmen und aktualisiert den Plan im Backend.

### Mögliche Implementierungen

Keine Idee

### Zusätzliche Informationen

- #37

**Comment by Schmarvinius** [comment]
Aufgrund keiner Aufteilung hab ich dem einfach mal Phase 0 und 1 gegeben

**Comment by laralngn** [comment]
Bisher ~ 4.5 Stunden

**Comment by laralngn** [comment]
Ersetzt durch Issues #293 und #294
